This notebook preprocesses the cell towers dataset into an efficient set of parquet files. First register for an API key with [opencellid](https://www.opencellid.org/) and then download the `cell_towers.csv.gz` file.  Unzip it and modify the `cell_towers_path` below to the path to your `cell_towers.csv` file.  Then execute this notebook to write out a compressed parquet to the `../data` directory.

In [31]:
cell_towers_path = "cell_towers.csv"

In [32]:
# Imports
!pip install dask
!pip install requests
!pip install dask-expr
import dask.dataframe as dd
import dask_expr as dx

import pandas as pd
import pyproj
from pyproj import Transformer
import requests
import os

Requirement already satisfied: dask in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (2024.3.1)
Requirement already satisfied: click>=8.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (2024.3.1)
Requirement already satisfied: packaging>=20.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (24.0)
Requirement already satisfied: partd>=1.2.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (1.4.1)
Requirement already satisfied: pyyaml>=5.3.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (6.0.1)
Requirement already satisfied: toolz>=0.10.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask) (7.0.2)
Requirement already satisfied: zipp>=0.5 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from importlib-metadata>=4.13.0->dask) (3.17.0)
Requirement already satisfied: locket in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from partd>=1.2.0->dask) (1.0.0)
Requirement already satisfied: requests in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from requests) (2024.2.2)
Collecting dask-expr
  Downloading dask_expr-1.0.5-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: dask==2024.3.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask-expr) (2024.3.1)
Collecting pyarrow>=7.0.0 (from dask-expr)
  Downloading pyarrow-15.0.2-cp39-cp39-macosx_10_15_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: pandas>=2 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask-expr) (2.2.1)
Requirement already satisfied: click>=8.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (8.1.7)
Requirement already satisfied: cloudpickle>=1.5.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (2024.3.1)
Requirement already satisfied: packaging>=20.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (24.0)
Requirement already satisfied: partd>=1.2.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (1.4.1)
Requirement already satisfied: pyyaml>=5.3.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (6.0.1)
Requirement already satisfied: toolz>=0.10.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from dask==2024.3.1->dask-expr) (7.0.2)
Requirement already satisfied: numpy<2,>=1.22.4 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from pandas>=2->dask-expr) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from pandas>=2->dask-expr) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from pandas>=2->dask-expr) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from pandas>=2->dask-expr) (2024.1)
Requirement already satisfied: zipp>=0.5 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from importlib-metadata>=4.13.0->dask==2024.3.1->dask-expr) (3.17.0)
Requirement already satisfied: locket in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from partd>=1.2.0->dask==2024.3.1->dask-expr) (1.0.0)
Requirement already satisfied: six>=1.5 in /Users/adamberesford/miniconda3/envs/dash-cell-towers/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2->dask-expr) (1.16.0)
Downloading dask_expr-1.0.5-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.6/183.6 kB 3.4 MB/s eta 0:00:00a 0:00:01
Downloading pyarrow-15.0.2-cp39-cp39-macosx_10_15_x86_64.whl (27.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 13.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: pyarrow, dask-expr
Successfully installed dask-expr-1.0.5 pyarrow-15.0.2

In [33]:
# From https://www.opencellid.org/downloads.php
# Field Descriptions: http://wiki.opencellid.org/wiki/Menu_map_view#Cells_database:
ddf = dd.read_csv(cell_towers_path)
ddf.head()

,radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal
0,UMTS,262,2,801,86355,0,13.285512,52.522202,1000,7,1,1282569574,1300155341,0
1,GSM,262,2,801,1795,0,13.276907,52.525714,5716,9,1,1282569574,1300155341,0
2,GSM,262,2,801,1794,0,13.285064,52.524000,6280,13,1,1282569574,1300796207,0
3,UMTS,262,2,801,211250,0,13.285446,52.521744,1000,3,1,1282569574,1299466955,0
4,UMTS,262,2,801,86353,0,13.293457,52.521515,1000,2,1,1282569574,1291380444,0

In [34]:
# Categorize radio
ddf['radio'] = ddf.radio.astype('category')

# Created and updated to datetime integers
ddf['created'] = dd.to_datetime(ddf.created, unit='s').astype('int')
ddf['updated'] = dd.to_datetime(ddf.updated, unit='s').astype('int')

# Filter out outliers created before 2003
ddf = ddf[dd.to_datetime(ddf.created) >= '2003']

In [35]:
# convert lon/lat to epsg:3857 (psuedo-mercator) so generated images
# can be overlayed on a Mercator projected map
transformer = Transformer.from_crs("epsg:4326", "epsg:3857")
def to3857(df):
    x_3857, y_3857 = transformer.transform(df.lat.values, df.lon.values)
    return df.assign(x_3857=x_3857, y_3857=y_3857)

ddf = ddf.map_partitions(to3857)

ddf.head()

,radio,mcc,net,area,cell,unit,lon,lat,range,samples,changeable,created,updated,averageSignal,x_3857,y_3857
0,UMTS,262,2,801,86355,0,13.285512,52.522202,1000,7,1,1282569574000000000,1300155341000000000,0,1.478936e+06,6.895103e+06
1,GSM,262,2,801,1795,0,13.276907,52.525714,5716,9,1,1282569574000000000,1300155341000000000,0,1.477979e+06,6.895745e+06
2,GSM,262,2,801,1794,0,13.285064,52.524000,6280,13,1,1282569574000000000,1300796207000000000,0,1.478887e+06,6.895432e+06
3,UMTS,262,2,801,211250,0,13.285446,52.521744,1000,3,1,1282569574000000000,1299466955000000000,0,1.478929e+06,6.895019e+06
4,UMTS,262,2,801,86353,0,13.293457,52.521515,1000,2,1,1282569574000000000,1291380444000000000,0,1.479821e+06,6.894977e+06

In [36]:
# Download network info for mcc/mnc from 'https://cellidfinder.com/mcc-mnc'
# html = requests.get('https://cellidfinder.com/mcc-mnc')
# tables = pd.read_html(html.content)
# mcc_mnc_df = pd.concat(tables).reset_index(drop=True)

# Create description column as Network, falling back to "Operator or branch" if Network not found
# mcc_mnc_df['Description'] = mcc_mnc_df.Network.where(
#     ~pd.isnull(mcc_mnc_df.Network), mcc_mnc_df['Operator or brand name']
# )

# Drop unneeded columns
# codes = mcc_mnc_df.drop(['Network', 'Operator or brand name'], axis=1)
# codes.head()

ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.

In [ ]:
# Categorize non-numeric columns
# for col, dtype in codes.dtypes.items():
#     if dtype == 'object':
#         codes[col] = codes[col].astype('category')

In [ ]:
# Merge mnc/mcc info with cell towers dataset
# ddf_merged = ddf.merge(codes, left_on=['mcc', 'net'], right_on=['MCC', 'MNC'], how='left')
ddf_merged = ddf

Dask DataFrame Structure:
                            radio    mcc    net   area   cell   unit      lon      lat  range samples changeable created updated averageSignal   x_3857   y_3857    MCC    MNC           Status      Description
npartitions=56
                category[unknown]  int64  int64  int64  int64  int64  float64  float64  int64   int64      int64   int64   int64         int64  float64  float64  int64  int64  category[known]  category[known]
                              ...    ...    ...    ...    ...    ...      ...      ...    ...     ...        ...     ...     ...           ...      ...      ...    ...    ...              ...              ...
...                           ...    ...    ...    ...    ...    ...      ...      ...    ...     ...        ...     ...     ...           ...      ...      ...    ...    ...              ...              ...
                              ...    ...    ...    ...    ...    ...      ...      ...    ...     ...        ...     ...     ...           ...      ...      ...    ...    ...              ...              ...
                              ...    ...    ...    ...    ...    ...      ...      ...    ...     ...        ...     ...     ...           ...      ...      ...    ...    ...              ...              ...
Dask Name: merge, 1121 tasks

In [ ]:
# Write parquet file to ../data directory
os.makedirs('../data', exist_ok=True)
parquet_path = '../data/cell_towers.parq'
ddf_merged.to_parquet(parquet_path, compression='snappy')

In [ ]:
# Read and display the first three rows (Transpose so can see all of the columns)
dd.read_parquet(parquet_path).head(3).T

index                            0                    1                    2
radio                         UMTS                  GSM                  GSM
mcc                            262                  262                  262
net                              2                    2                    2
area                           801                  801                  801
cell                         86355                 1795                 1794
unit                             0                    0                    0
lon                        13.2855              13.2769              13.2851
lat                        52.5222              52.5257               52.524
range                         1000                 5716                 6280
samples                          7                    9                   13
changeable                       1                    1                    1
created        1282569574000000000  1282569574000000000  1282569574000000000
updated        1300155341000000000  1300155341000000000  1300796207000000000
averageSignal                    0                    0                    0
x_3857                 1.47894e+06          1.47798e+06          1.47889e+06
y_3857                  6.8951e+06          6.89575e+06          6.89543e+06
MCC                            262                  262                  262
MNC                              2                    2                    2
Status                 Operational          Operational          Operational
Description       Vodafone D2 GmbH     Vodafone D2 GmbH     Vodafone D2 GmbH